apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-test
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-test
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx-test-container
          image: nginx:latest
          ports:
            - containerPort: 80 
  selector:
    matchLabels:
      app: nginx-test