apiVersion: v1
kind: Service
metadata:
  name: vollmed-service
spec:
  selector:
    app: vollmed
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vollmed-ingress
spec:
  rules:
    - host: vollmed.inovvati.corp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vollmed-service
                port:
                  number: 80
