
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voll-med-mysql-perssistvolmeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow
