apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias
      image: aluracursos/mysql-db:1
      ports: 
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-noticias-configmap
      # env:
      #   - name: MYSQL_ROOT_PASSWORD
      #     valueFrom:
      #       configMapKeyRef:
      #         name: db-noticias-configmap
      #         key: MYSQL_ROOT_PASSWORD
      #   - name: MYSQL_DATABASE
      #     valueFrom:
      #       configMapKeyRef:
      #         name: db-noticias-configmap
      #         key: MYSQL_DATABASE
      #   - name: MYSQL_PASSWORD
      #     valueFrom:
      #       configMapKeyRef:
      #         name: db-noticias-configmap
      #         key: MYSQL_PASSWORD

      #   - name: "MYSQL_ROOT_PASSWORD"
      #     value: "123456"
      #   - name: "MYSQL_DATABASE"
      #     value: "noticias"
      #   - name: "MYSQL_PASSWORD"
      #     value: "123456"
