apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume
          name: primeiro-volume

    - name: jenkins-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume
          name: primeiro-volume
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /home/VolumeTeste
        type: DirectoryOrCreate
