apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meu-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfsprodinfra  # Para usar a StorageClass padrão
  resources:
    requests:
      storage: 100Gi  # Solicitação de 5 gigabytes de armazenamento
